#!/bin/sh
# $Revision$
# $Date$
#
### BEGIN INIT INFO
# Provides:          xivo-sysconfd
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Should-Start:      rabbitmq-server
# Should-Stop:       rabbitmq-server
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup daemon script for XIVO sysconf daemon
### END INIT INFO
#
set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMONNAME=xivo-sysconfd
DAEMON=/usr/bin/$DAEMONNAME
PIDFILE=/var/run/$DAEMONNAME.pid

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

case "$1" in
  start)
    log_daemon_msg "Starting" "$DAEMONNAME"
    if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON;
    then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping" "$DAEMONNAME"
    if start-stop-daemon --stop --quiet --oknodo --retry 5 --pidfile $PIDFILE;
    then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    rm -f $PIDFILE
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON "XIVO $DAEMONNAME" && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
