version: '3'
services:

  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  sysconfd:
    image: wazoplatform/wazo-sysconfd-tests
    ports:
      - "8668"
    volumes:
      - "../..:/usr/local/src/wazo-sysconfd"
      - "./etc/wazo-sysconfd/conf.d/50-default.yml:/etc/wazo-sysconfd/conf.d/50-default.yml"
      - "./bin/mock-command:/usr/local/bin/mock-command"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.9/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/opt/venv/lib/python3.9/site-packages/xivo_bus"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq
