FROM wazoplatform/wazo-sysconfd

ENV PYTHONDONTWRITEBYTECODE='true'

COPY . /usr/local/src/wazo-sysconfd
COPY integration_tests/assets/bin/mock-command /usr/local/bin/
WORKDIR /usr/local/src/wazo-sysconfd
RUN python setup.py develop \
    && adduser --quiet --system --group --no-create-home --home /var/lib/asterisk asterisk \
    && mkdir -p /etc/cron.d \
    && mkdir -p /etc/local \
    && mkdir -p /var/lib/wazo \
    && ln -s /usr/local/bin/mock-command /bin/systemctl \
    && ln -s /usr/local/bin/mock-command /usr/bin/asterisk \
    && ln -s /usr/local/bin/mock-command /usr/local/bin/dhcpd-update \
    && ln -s /usr/local/bin/mock-command /usr/local/bin/hostname \
    && ln -s /usr/local/bin/mock-command /usr/local/bin/wazo-service \
    && ln -s /usr/local/bin/mock-command /usr/sbin/xivo-create-config \
    && ln -s /usr/local/bin/mock-command /usr/sbin/xivo-manage-slave-services \
    && ln -s /usr/local/bin/mock-command /usr/sbin/xivo-monitoring-update \
    && ln -s /usr/local/bin/mock-command /usr/sbin/xivo-update-config \
    && install -D /dev/null /etc/postgresql/11/main/pg_hba.conf \
    && install -D /dev/null /etc/postgresql/11/main/postgresql.conf \
    && true

