FROM wazoplatform/wazo-sysconfd

ENV PYTHONDONTWRITEBYTECODE='true'

COPY . /usr/local/src/xivo-sysconfd
COPY integration_tests/assets/bin/mock-command /usr/local/bin/
WORKDIR /usr/local/src/xivo-sysconfd
RUN python setup.py develop \
    && adduser --quiet --system --group --no-create-home --home /var/lib/asterisk asterisk \
    && ln /usr/local/bin/mock-command /usr/local/bin/dhcpd-update \
    && ln /usr/local/bin/mock-command /usr/sbin/xivo-create-config \
    && ln /usr/local/bin/mock-command /usr/sbin/xivo-update-config \
    && ln /usr/local/bin/mock-command /usr/sbin/xivo-monitoring-update \
    && ln /usr/local/bin/mock-command /usr/bin/asterisk \
    && true

