# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-sysconfd/conf.d/

xivo_config_path: /etc/xivo
templates_path: /usr/share/wazo-sysconfd/templates
custom_templates_path: /etc/xivo/sysconfd/custom-templates
backup_path: /var/backups/wazo-sysconfd

debug: false
log_level: info
log_file: /var/log/wazo-sysconfd.log

rest_api:
  listen: 127.0.0.1
  port: 8668

resolvconf:
  hostname_file: /etc/hostname
  hosts_file: /etc/hosts
  resolvconf_file: /etc/resolv.conf

network:
  interfaces_file: /etc/network/interfaces

wizard:
  templates_path: /usr/share/xivo-config/templates
  custom_templates_path: /etc/xivo/custom-templates

commonconf:
  commonconf_file: /etc/xivo/common.conf
  commonconf_generate_cmd: /usr/sbin/xivo-create-config
  commonconf_update_cmd: /usr/sbin/xivo-update-config
  commonconf_monit: /usr/sbin/xivo-monitoring-update

monit:
  monit_checks_dir: /usr/share/xivo-monitoring/checks
  monit_conf_dir: /etc/monit/conf.d

request_handlers:
  synchronous: false

bus:
  username: guest
  password: guest
  host: localhost
  port: 5672
  exchange_name: wazo-headers
  exchange_type: headers
